In [ ]:
#arrays

import numpy

def arrays(arr):
    rev = numpy.array(arr[::-1], float)
    return(rev)
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

In [ ]:
#shape_and_reshape

import numpy
arr = input().split()
my_arr = numpy.array(arr, int)
print (numpy.reshape(my_arr, (3,3)))

In [ ]:
#transpose_and_flatten

import numpy as np
n,m = map(int, input().split())
a1 = []
for i in range(n):
    array1 = input().strip().split()
    arr = np.array(array1, int)
    a1.append(arr)
a1 = np.array(a1)
print(a1.transpose())
print(a1.flatten())

In [ ]:
#concatenate

import numpy as np
n,m,p = map(int, input().split())
arr_1 = np.array([input().split() for i in range(n)], int)
arr_2 = np.array([input().split() for i in range(m)], int)
arr = np.concatenate((arr_1, arr_2), axis = 0)
print(arr)

In [ ]:
#zeros_and_ones

import numpy as np
dimensions = list((map(int, input().split())))
print(np.zeros((dimensions), dtype = np.int))
print(np.ones((dimensions), dtype = np.int))

In [ ]:
#eye_and_identity

import numpy as np
np.set_printoptions(legacy = '1.13')
a, b = map(int, input().split())
print(np.eye(a, b, k = 0))

In [ ]:
#Array_Mathematics

import numpy as np

n, m = map(int, input().split())

a = np.array([input().split() for i in range(n)], int)
b = np.array([input().split() for i in range(n)], int)
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

In [ ]:
#sum_and_prod

import numpy as np
n, m = map(int, input().split())
arr = np.array([input().split()  for i in range(n)], int)
arr.reshape(n,m)
summation = np.sum(arr, axis = 0)
product = np.prod(summation, axis = 0)
print(product)

In [7]:
#floor_ceil_rint

import numpy as np
np.set_printoptions(sign = ' ')
arr = np.array(input().split(), float)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [ ]:
#min_and_max

import numpy as np
n,m = map(int, input().split())
arr = np.array([input().split() for i in range(n)], int)
maximum = np.max(np.min(arr, axis = 1))
print(maximum)

In [ ]:
#mean_var_std

import numpy as np
n,m = map(int, input().split())
arr = np.array([input().split() for i in range(n)], int)
print(np.mean(arr, axis = 1))
print(np.var(arr, axis = 0))
print(np.around(np.std(arr), decimals = 11))

In [ ]:
#dot_and_cross

import numpy as np
n = int(input())
arr_1 = np.array([input().split() for i in range(n)], int)
arr_2 = np.array([input().split() for i in range(n)], int)
print(np.dot(arr_1, arr_2))

In [ ]:
#inner_and_outer

import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A, B))
print(np.outer(A, B))

In [ ]:
#polynomials

import numpy
p = list(map(float, input().split()))
x = float(input())
p = numpy.array(p)
print(numpy.polyval(p,x))

In [ ]:
#linear_algebra

import numpy
p = list(map(float, input().split()))
x = float(input())
p = numpy.array(p)
print(numpy.polyval(p,x))